### ISSUE TITLE
Bad file and cannot install

### ISSUE THREAD

**Issue by LoneFuckingWolf** [Xeeynamo/KH3SaveEditor#29]
Hi, since this new update came out, I've been having trouble installing it.

To start, when I boot up the .exe file, a window pops up telling me that the file may put my PC at risk. I run it anyway, and after the installation runs, it instantly fails and I get an error message that won't go away unless I open up task manager and end the task.

This seems very peculiar and it may be something you guys will want to look into.

**Comment by Xeeynamo** [comment]
Hey!
The new builds come into a single executable file, but it's nothing more than a ZIP archive that auto-extracts itself and run. Some antivirus flags it as a false positive for that reason.

You have three options:
1. Let your antivirus to ignore that specific file.
2. Right click on the executable and extract the content. Then run it as you always did with the previous versions.
3. Compile the source code using Visual Studio 2019 (slow and not that recommended)

I am closing this issue since it is a isolated case. But I will continue to read your comments and help you through :)
