### ISSUE TITLE
Kingdom hearts 3 save data is corrupted

### ISSUE THREAD

**Issue by Swagmastersans** [Xeeynamo/KH3SaveEditor#30]
I started to use this tonight but every time I edit the save file and go to use it says it's corrupted is there a step I am missing to use this.

**Comment by Xeeynamo** [comment]
Could you attach the save before using the Save Editor and after the game started to say it's corrupted?

**Comment by Swagmastersans** [comment]
Sure sorry it took so long to respond I had stuff to work on but it isn't letting me send the bin file

**Comment by Xeeynamo** [comment]
Can you upload it somewhere else? Like Mega, Google Drive, OneDrive, etc.

**Comment by Swagmastersans** [comment]
Here is the google drive for both the original is the one without the 2 in the name.
https://drive.google.com/open?id=1NHVzsFPKB_xF4Ela4RfEzVn2-xlAMWFi
https://drive.google.com/open?id=1zn1p1BvhJLURhN0AsRpQ8VpOBYRRQWEO

**Comment by Xeeynamo** [comment]
I digged very deep to understand what was the issue and I never found anything useful. The file `__data__slot_62` works on my end. The only data that has been changed were the shortcuts and that would not corrupt the save.
I suspect that something went wrong when you imported the file back to Save Wizard?

I am closing the issue since the problem was not to the save editor end.
