### ISSUE TITLE
FF7R Missing item name request

### ISSUE THREAD

**Issue by wmxp** [Xeeynamo/KH3SaveEditor#65]
Just a very small bug, you have two instances of "Gothic Bangle" in the FF7R item list. The second listing, closest to Chain Bangle, should in fact be Cog Bangle.
![image](https://user-images.githubusercontent.com/30638431/81479013-bccf8680-91d5-11ea-80e2-aa0c45f5e139.png)

Also, not sure if it's a bug in your app or not, but the starting equipment "Bronze Bangle" reads as owning x3 in all my saves files within your editor. In game, that item is listed as owning x2 - the starting equipment that cannot be sold.

Thanks for all your hard work, it's wonderful to be able to tinker with FF7R this early out of the gate! <3

**Comment by Xeeynamo** [comment]
I fixed the name to Cog Bangle, you can now see the name fixed in the Inventory section. Thanks for letting me know!

About the Bronze Bangle, believe or not but it is normal. When you start the game, three characters do have the Bronze Bangle equipped: Cloud, Tifa and Red XIII. Since Red can not be seen in-game and his equipment can not be changed, the game will always show one Bronze Bangle less than the real amount! To fix it, go to "Characters" tab and put a "-1" to Red's Armor.

I am closing here since I fixed the main issue. But if you have more questions, please let me know!
