### ISSUE TITLE
Can't add materia to added weapons

### ISSUE THREAD

**Issue by bokkoman** [Xeeynamo/KH3SaveEditor#66]
First of, thanks for updating the app! Adding weapons works.
But unfortunately, adding materia to an added weapon does not work. When you select a materia to a slot, it stays blank.

**Comment by Xeeynamo** [comment]
It works for me. When you click "Empty", if you scroll up you can actually see the Materia there.
Did it helped?

**Comment by bokkoman** [comment]
I meant in the game. I add weapon in save editor, then in game i try to add materia.

**Comment by Xeeynamo** [comment]
Can you make a video?

**Comment by bokkoman** [comment]
> Can you make a video?

Yes, I'll make a video next time I'm playing.

**Comment by bokkoman** [comment]
https://streamable.com/7yuqjb

Here is the video you asked for. I hope it is clear enough.

**Comment by Xeeynamo** [comment]
Now I got what you were talking about, and it confirms what was for me something suspicious. I am afraid that there are some places in the save that have yet to be discovered in order to add successfully a weapon from scratch. I suggest to remove it from the editor and obtain it legally.

I am sorry but I have no idea how can I help you further :/ and I am sorry that the functionality in my editor was not working as expected.

**Comment by bokkoman** [comment]
> Now I got what you were talking about, and it confirms what was for me something suspicious. I am afraid that there are some places in the save that have yet to be discovered in order to add successfully a weapon from scratch. I suggest to remove it from the editor and obtain it legally.
> 
> I am sorry but I have no idea how can I help you further :/ and I am sorry that the functionality in my editor was not working as expected.

You don't have to apologise. I already obtained it later in game. You know what is funny. Once I obtained the "original" the materia was already assigned to some slots... How weird is that!
Anyway, thanks for this editor! Everything else worked fine, for the things i used it for!
