### ISSUE TITLE
Issue with PS4 Wizard

### ISSUE THREAD

**Issue by jonattttt** [Xeeynamo/KH3SaveEditor#73]
I know not an issue with your program but I'm trying to see if anyone else is having this problem. Since the most recent update of PS4 wizard. When I try to import the edited FF7R saves back into PS4 Wizard it reverts the saves back to the way they were before editing. Is anyone else having this issue?

**Comment by Xeeynamo** [comment]
According to people that uses SW in my Discord server, I am afraid that you are the only one who ran into this issue. I would suggest to try again or use SW Beta version, which is supposed to fix various bugs when importing a save in the Advanced Mode.

I will close the issue here. For anything related to Save Wizard, I suggest to contact them. I do not think you will have problems, but either case good luck :)
